services:
  gateway:
    build: .
    image: binarybrain/gateway:0.0.1
    container_name: gateway
    ports:
      - "5000:5000"
    environment:
      EUREKA_SERVER_URL: http://host.docker.internal:8070/eureka/
