server:
  port: 5001

spring:
  application:
    name: OCM-USER-REGISTRATION

  config:
    import: optional:classpath:secret.properties

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/OCM_userDB}
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  profiles:
    active: dev

  servlet:
    multipart:
      enabled: true
      max-file-size: 7MB
      max-request-size: 7MB

photo:
  upload-dir: ${PHOTO_UPLOAD_DIR:./uploads/images/}
opencv:
  api-key: sampleApiKey

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8070/eureka/}