server:
  port: 5001

spring:
  application:
  name: OCM User Registration

  config:
    import: classpath:secret.properties


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/OCM_userDB
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

