server:
  port: 5000

spring:
  application:
    name: GATEWAY-SERVICE

  config:
    import: classpath:secret.properties

  cloud:
    gateway:
      routes:
        - id: USER-MICROSERVICE
          uri:
            http://localhost:5001
          predicates:
            - Path=/api/user/**
          filters:
            - JwtAuthFilter

        - id: CLASSROOM-MICROSERVICE
          uri:
            http://localhost:5002
          predicates:
            - Path=/api/v1/private/classroom/**
          filters:
            - JwtAuthFilter

        - id: COURSE-MICROSERVICE
          uri:
            http://localhost:5003
          predicates:
            - Path=/api/v1/private/course/**
          filters:
            - JwtAuthFilter

        - id: Task-MICROSERVICE
          uri:
            http://localhost:5004
          predicates:
            - Path=/api/v1/private/task/**
          filters:
            - JwtAuthFilter

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
