server:
  port: 5000

spring:
  application:
    name: GATEWAY-SERVICE

  config:
    import: optional:classpath:secret.properties

  cloud:
    gateway:
      routes:
        - id: USER-MICROSERVICE
          uri: lb://USER-MICROSERVICE
          predicates:
            - Path=/api/user/**
          filters:
            - JwtAuthFilter

        - id: CLASSROOM-MICROSERVICE
          uri: lb://CLASSROOM-MICROSERVICE
          predicates:
            - Path=/api/v1/private/classroom/**
          filters:
            - JwtAuthFilter

        - id: COURSE-MICROSERVICE
          uri: lb://COURSE-MICROSERVICE
          predicates:
            - Path=/api/v1/private/course/**
          filters:
            - JwtAuthFilter

        - id: TASK-MICROSERVICE
          uri: lb://TASK-MICROSERVICE
          predicates:
            - Path=/api/v1/private/task/**
          filters:
            - JwtAuthFilter

        - id: TASK-SUBMISSION-MICROSERVICE
          uri: lb://TASK-SUBMISSION-MICROSERVICE
          predicates:
            - Path=/api/v1/private/submission/**
          filters:
            - JwtAuthFilter

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8070/eureka/}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: USER-MICROSERVICE
        url: /api/user/v3/api-docs
      - name: CLASSROOM-MICROSERVICE
        url: /api/v1/private/classroom/v3/api-docs
      - name: COURSE-MICROSERVICE
        url: /api/v1/private/course/v3/api-docs
      - name: TASK-MICROSERVICE
        url: /api/v1/private/task/v3/api-docs
      - name: TASK-SUBMISSION-MICROSERVICE
        url: /api/v1/private/submission/v3/api-docs
  api-docs:
    path: /v3/api-docs