server:
  port: 5005

spring:
  application:
    name: TASK-SUBMISSION-MICROSERVICE

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 1MB

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://${SPRING_DATASOURCE_HOSTNAME}/OCM_submission}

    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

file:
  upload-dir: ${FILE_UPLOAD_DIR:./uploads/submission/}

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8070/eureka/}

springdoc:
  swagger-ui:
    enabled: true
    path: /api/v1/private/submission/swagger-ui.html
    try-it-out-enabled: true
  api-docs:
    path: /api/v1/private/submission/v3/api-docs
  default-produces-media-type: application/json
  show-actuator: false
  use-management-port: false
  remove-broken-reference-definitions: true
  override-with-gateway-url: true
  server:
    url: http://localhost:5000