server:
  port: 5003

task-service:
  url: http://taskservice:5004/
user-service:
  url: http://userservice:5001/

spring:
  application:
    name: COURSE-MICROSERVICE

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://${SPRING_DATASOURCE_HOSTNAME}/OCM_course}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8070/eureka/}

springdoc:
  swagger-ui:
    enabled: true
    path: /api/v1/private/course/swagger-ui.html
    try-it-out-enabled: true
    tags-sorter: ordered
    operations-sorter: alpha
  api-docs:
    path: /api/v1/private/course/v3/api-docs
  default-produces-media-type: application/json
  show-actuator: false
  use-management-port: false
  remove-broken-reference-definitions: true
  override-with-gateway-url: true
  server:
    url: http://localhost:5000

