server:
  port: 5003

task-service:
  url: http://taskservice:5004/
user-service:
  url: http://userservice:5001/

spring:
  application:
    name: COURSE-MICROSERVICE

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/OCM_course}
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8070/eureka/}

springdoc:
  api-docs:
    path: /api/v1/private/course/v3/api-docs
  swagger-ui:
    path: /api/v1/private/course/swagger-ui.html
