version: "3.8"

services:
  mysql-task:
    image: mysql:8
    container_name: mysql-task
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: OCM_task
    ports:
      - "3309:3306"
    networks:
      - mynetwork

  taskservice:
    build: .
    image: binarybrain/taskservice:0.0.1
    container_name: taskservice
    depends_on:
      - mysql-task
    ports:
      - "5004:5004"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-task:3306/OCM_task
      EUREKA_SERVER_URL: http://host.docker.internal:8070/eureka/
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
