server:
  port: 5002

user-service:
  url: http://localhost:5001/
course-service:
  url: http://localhost:5002/

spring:
  application:
    name: CLASSROOM-MICROSERVICE

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/OCM_classroom
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
