server:
  port: 5002
spring:
  application:
    name: Classroom Microservice

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/OCM_classroom
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
