server:
  port: 5004

spring:
  application:
    name: TASK-MICROSERVICE

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/OCM_task}
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8070/eureka/}

springdoc:
  swagger-ui:
    enabled: true
    path: /api/v1/private/task/swagger-ui.html
    try-it-out-enabled: true
  api-docs:
    path: /api/v1/private/task/v3/api-docs
  default-produces-media-type: application/json
  show-actuator: false
  use-management-port: false
  remove-broken-reference-definitions: true
  override-with-gateway-url: true
  server:
    url: http://localhost:5000


