name: SonarCloud Analysis

on:
  push:
  pull_request:

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for SonarCloud branch analysis

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build All Modules
        run: |
          mvn clean install -Dspring.profiles.active=test jacoco:report-aggregate -DskipTests=false
          echo "Verifying generated files:"
          find . -path "*/target/classes" -exec ls -la {} \; || echo "Some target/classes directories missing!"
          find . -path "*/target/site/jacoco/jacoco.xml" -exec ls -la {} \; || echo "Some JaCoCo reports missing!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2.2.0
        with:
          projectBaseDir: .  # Root directory for multi-module project
          args: >
            -X
            -Dsonar.projectKey=Learnathon-By-Geeky-Solutions_binarybrain
            -Dsonar.organization=learnathon-by-geeky-solutions
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco-aggregate/jacoco.xml
            -Dsonar.java.binaries=**/target/classes
            -Dsonar.sources=**/src/main/java
            -Dsonar.tests=**/src/test/java
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
