name: SonarCloud Analysis

on:
  push:
  pull_request:

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for SonarCloud branch analysis

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build All Modules
        run: |
          mvn clean verify -Dspring.profiles.active=test jacoco:report -DskipTests=false
          echo "Verifying generated files:"
          find . -path "*/target/classes" -exec ls -la {} \; || echo "Some target/classes directories missing!"
          find . -path "*/target/site/jacoco/jacoco.xml" -exec ls -la {} \; || echo "Some JaCoCo reports missing!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2.2.0
        with:
          projectBaseDir: .  # Root directory for multi-module project
          args: >
            -X
            -Dsonar.projectKey=Learnathon-By-Geeky-Solutions_binarybrain
            -Dsonar.organization=learnathon-by-geeky-solutions
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.binaries=common-exception-handler/target/classes,classroom-microservice/target/classes,course-microservice/target/classes,eureka-server/target/classes,gateway/target/classes,online-classroom-management/target/classes,task-microservice/target/classes,task-submission-service/target/classes
            -Dsonar.coverage.jacoco.xmlReportPaths=common-exception-handler/target/site/jacoco/jacoco.xml,classroom-microservice/target/site/jacoco/jacoco.xml,course-microservice/target/site/jacoco/jacoco.xml,eureka-server/target/site/jacoco/jacoco.xml,gateway/target/site/jacoco/jacoco.xml,online-classroom-management/target/site/jacoco/jacoco.xml,task-microservice/target/site/jacoco/jacoco.xml,task-submission-service/target/site/jacoco/jacoco.xml
            -Dsonar.java.binaries=common-exception-handler/target/classes,classroom-microservice/target/classes,course-microservice/target/classes,eureka-server/target/classes,gateway/target/classes,online-classroom-management/target/classes,task-microservice/target/classes,task-submission-service/target/classes
            -Dsonar.sources=common-exception-handler/src/main/java,classroom-microservice/src/main/java,course-microservice/src/main/java,eureka-server/src/main/java,gateway/src/main/java,online-classroom-management/src/main/java,task-microservice/src/main/java,task-submission-service/src/main/java
            -Dsonar.tests=common-exception-handler/src/test/java,classroom-microservice/src/test/java,course-microservice/src/test/java,eureka-server/src/test/java,gateway/src/test/java,online-classroom-management/src/test/java,task-microservice/src/test/java,task-submission-service/src/test/java

        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
